name: Deploy

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: SSH and Deploy
              env:
                  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
              run: |
                  echo "$SSH_PRIVATE_KEY" > keyfile
                  chmod 600 keyfile
                  mkdir -p ~/.ssh
                  cp known_hosts ~/.ssh/known_hosts
                  ssh -V
                  ssh -t -i keyfile -o "StrictHostKeyChecking=no" -o "BatchMode=yes" ubuntu@ec2-16-170-155-73.eu-north-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
